package_assets:         on          # (on, off, always)
embed_assets:           off          # (on, off, datauri)
compress_assets:        on          # (on, off)
gzip_assets:            on          # (on, off)
#template_function:      _.template  # (defaults to the built-in micro-templating)
package_path:           packages    # (defaults to assets)
javascript_compressor:  closure     # (yui, closure)
compressor_options:
  compilation_level: WHITESPACE_ONLY

#
# REMINDER Don't use pre compiled/minified js
# It will most likely kill the jammit package
#

javascripts:
  common:
    #
  posts:
    #
    
stylesheets:
  print:
    #
  common:
    - public/stylesheets/screen.css
    
    
