package_assets:         on          # (on, off, always)
embed_assets:           off          # (on, off, datauri)
compress_assets:        on          # (on, off)
gzip_assets:            on          # (on, off)
#template_function:      _.template  # (defaults to the built-in micro-templating)
package_path:           packages    # (defaults to assets)
javascript_compressor:  closure     # (yui, closure)
compressor_options:
  compilation_level: WHITESPACE_ONLY

#
# REMINDER Don't use pre compiled/minified js
# It will most likely kill the jammit package
#

javascripts:
  common:
    - public/javascripts/vendor/jquery/jquery.1.5.2.js
    - public/javascripts/vendor/jquery-ui-1.8.12.custom/development-bundle/ui/jquery-ui-1.8.12.custom.js
    - public/javascripts/lib/Object.js
    - public/javascripts/lib/String.js
    - public/javascripts/vendor/jquery/jquery.autobox.js
    - public/javascripts/vendor/jquery/jquery.disable.js
    - public/javascripts/vendor/formValidator.2.2/js/languages/jquery.validationEngine-en.js
    - public/javascripts/vendor/formValidator.2.2/js/jquery.validationEngine.js
    - public/javascripts/application.js
  posts:
    #
  comments:
    #
    
stylesheets:
  print:
    #
  common:
    - public/stylesheets/screen.css
    
    
